## Oscar Hernández Terán
Bachelor's degree:
        Geophysical Engineer

## Variable names
#### The recommended convenction is that variable names are typed in lowercase letters and words are separated by a underscore 

In [1]:
## Variable names
z = 100
y = 6.0
s = "Artificial"
data_science = true
bool = false

false

## Operators

In [2]:
a = 1
b = 5.5
c = 3

## Arithmetic
println("Sum:              ", a+b)
println("Subtract:         ", a-b)
println("Multiplication:   ", a*c)
println("Division:         ", a/b)
println("Power:            ", b^3)

println("----------------------------------------------------------")
## Updating operators
x = 2
y = 3
println("x = y + 2:   ", x += 2)
println("y = y - 2:   ", y -= 2)
println("x = x * 10:  ", x *= 10)

println("----------------------------------------------------------")
## Comparison
println(4 == 4)
println(5 != 8)
println(3 <= 2)

Sum:              6.5
Subtract:         -4.5
Multiplication:   3
Division:         0.18181818181818182
Power:            166.375
----------------------------------------------------------
x = y + 2:   4
y = y - 2:   1
x = x * 10:  40
----------------------------------------------------------
true
true
false


## Operator precedence

#### When constructing expressions with multiple operators, the order in which these operators are applied to the expression is known as operator precedence.

In [3]:
x = 2
y = 3
z = 4
println(x*y+z^2)
println(x*(y+(z^2)))
println((x*y)+(z^2))

22
38
22


## Types
#### The Julia float type and all operations performed on it adhere to IEEE 754 standard (Zuras et al., 2018)
#### In Julia, a string is a sequence of Unicode code points, using UTF-8 encoding.
#### Char is a numeric value representing a Unicode code point

In [4]:
## Computer's architecture type
println(Sys.WORD_SIZE)

## Size of te default primitive
println(typemax(Int))

64
9223372036854775807


In [5]:
# Integers
int_1 = 1
println(typeof(int_1))
println("------------------------------------")

# Floats
f_1 = 1.0
f_2 = 15e-5
# Format Float32
f_3 = 2.5f-4
println(typeof(f_3))

# Digit separation 
println(7.4_4 == 7.44)

# Values Errors
println(isnan(0/0))
println(isinf(10/0))
println(isinf(10/0))
println("------------------------------------")

Int64
------------------------------------
Float32
true
true
true
true
------------------------------------


In [6]:
# Strings
# The strings are immutable, and are defined by double or triple quotes
s1 = "Hello world"
s2 = """ I have a "quote" character """
println(typeof(s2))
println(s2)

# Strings ca be sliced
my_string = "Julia is very fast"
println(my_string[1:8])
println(my_string[end])
println(my_string[end-3:end])

# The operator concatenation is *
my_string_2 = " and works for Data Science"
message = my_string * my_string_2
# Another way
message_2 = string(my_string, my_string_2)
println(message)
println(message_2)
println("------------------------------------")

String
 I have a "quote" character 
Julia is
t
fast
Julia is very fast and works for Data Science
Julia is very fast and works for Data Science
------------------------------------


### Strings can be compared lexicographically using comparison operators.
#### Some methods of strings are:
1. findfirst(pat, str)
2. occursin(substr, str)
3. repeat(str, n)
4. lenth(str)
5. replace(str, ptn => rep)

#### Julia fully supports regular expressions (regexes):
1. occursin(regex, str)
2. match(regex, str)
3. eachmatch(regex, str)

## Tuples 
#### Tuples are a Julia type. Fields are accessed by ther index, and are defined using brackets (). Tuples are inmmutables.

In [7]:
tup1 = (2., 5.6, 8.9, 2. ,5.)
tup2 = (8, "Julia", 9.0, 4.7, "Data")

println(typeof(tup1))
println(typeof(tup2))

a,b,c = ("Science", 9004, "Covid")
println(a)
println(b)
println(c)

NTuple{5,Float64}
Tuple{Int64,String,Float64,Float64,String}
Science
9004
Covid


## Arrays
#### An array is a multidimensional grid that stores objects of any type.

In [8]:
# Definition with type and dimension
a1 = Array{Int64}(undef, 5)
println(a1)

a2 = Array{Int64}(undef, (2,2))
println(a2)

[139960192001392, 139960192001392, 139959461493168, 139959461493200, 139959461493232]
[139960101150832 139960101150960; 139960101150896 139959487693104]


#### In Julia, [] can also be used to generate arrays.

#### Julia has many built-in functions that generate specific kinds of arrays. Here are some useful ones:
1. zeros(T, d1, ..)-------Matrix of zeros
2. ones(T, d1, ..)--------Matrix of ones
3. rand(T, d1, ..)--------Matrix of random numbers between 0 and 1
4. randn(T, d1, ..)-------Matrix of random numbers from the standar normal distribution
5. MatrixT(I, (n,n)-------Is the nxn identity matrix 
6. fill!(A, x)----------------Is the array A filled with value x

#### Note that, in te above, d1 can be a tuple specifying multiple dimensions.


#### Arrays can easily be concatenated in Julia:
1. vcat(A1, A2, ..) --------Concatenates arrays vertically
2. hcat(A1, A2, ..) --------Concatenates arrays hotizontally

In [9]:
# A vector
a3 = [1, 2, 3]

# A 1x3 column vector
a4 = [4 5 6]

# A matrix 2x3
m1 = [10 20 30 ; 90 91 92]

m2 = randn(Float64, (4,3))
m2

4×3 Array{Float64,2}:
 -1.30394    1.54453    0.166894
 -0.014866  -0.0107168  0.699948
 -0.918621  -0.0558607  0.030346
 -0.702463   1.29535    0.477379

In [10]:
# Utils methods
println(length(m2))
println(size(m2))
println(ndims(m2))

m2_c = deepcopy(m2)

m2_r = reshape(m2, (3,4))

12
(4, 3)
2


3×4 Array{Float64,2}:
 -1.30394   -0.702463   -0.0558607  0.699948
 -0.014866   1.54453     1.29535    0.030346
 -0.918621  -0.0107168   0.166894   0.477379

In [11]:
# Importing moduls
using LinearAlgebra
imat = Matrix{Int8}(I, (5,5))
imat

5×5 Array{Int8,2}:
 1  0  0  0  0
 0  1  0  0  0
 0  0  1  0  0
 0  0  0  1  0
 0  0  0  0  1

### Index

In [12]:
m2_r

3×4 Array{Float64,2}:
 -1.30394   -0.702463   -0.0558607  0.699948
 -0.014866   1.54453     1.29535    0.030346
 -0.918621  -0.0107168   0.166894   0.477379

In [13]:
println(m2_r[1:3])
println(m2_r[1,:])
println(m2_r[:,1])
println(m2_r[1:end,2])

[-1.3039432490715472, -0.014865999046136107, -0.9186211577586266]
[-1.3039432490715472, -0.7024631943475249, -0.05586068812487272, 0.6999478281769111]
[-1.3039432490715472, -0.014865999046136107, -0.9186211577586266]
[-0.7024631943475249, 1.544526391737921, -0.01071684586695944]


### Comprehensions

In [14]:
A1 = [sqrt(i) for i in [1,4,9,16,25]]
println(A1)

A2 = [i^2 for i in [1,2,3,4,5]]
println(A2)

[1.0, 2.0, 3.0, 4.0, 5.0]
[1, 4, 9, 16, 25]


## Dictionaries
In Julia, dictionaries are defines as associative collections consisting of a key-value. Dictionaries in Julia are created using the keyword Dict and types can de specified for both the key and the value. The keys are hashed and are always unique.

In [16]:
Dic1 = Dict()
Dic2 = Dict(1 => "Hi", 2 => "World")
Dic3 = Dict{Integer, String}(1 => "Hi", 2 => "World")
println(Dic1,"\n", Dic2, "\n", Dic3)

Dict{Any,Any}()
Dict(2 => "World",1 => "Hi")
Dict{Integer,String}(2 => "World",1 => "Hi")


Dictionaries can be created using a loop or using the generator syntax (Comprehensions)

In [19]:
meats = ["Fish", "Chicken", "Cown"]

# We inizializate the dict
Dict4 = Dict{Integer, String}()

for (n, fd) in enumerate(Dict4)
    Dict4[n] = fd
end

wine = ["red", "white", "rose"]
Dict5 = Dict{Integer, String}(i => wine[i] for i in 1:length(wine))

println(Dict4,"\n", Dict5)

Dict{Integer,String}()
Dict{Integer,String}(2 => "white",3 => "rose",1 => "red")
