## Oscar Hernández Terán
Bachelor's degree:
        Geophysical Engineer

## Variable names
#### The recommended convenction is that variable names are typed in lowercase letters and words are separated by a underscore 

In [1]:
## Variable names
z = 100
y = 6.0
s = "Artificial"
data_science = true
bool = false

false

## Operators

In [2]:
a = 1
b = 5.5
c = 3

## Arithmetic
println("Sum:              ", a+b)
println("Subtract:         ", a-b)
println("Multiplication:   ", a*c)
println("Division:         ", a/b)
println("Power:            ", b^3)

println("----------------------------------------------------------")
## Updating operators
x = 2
y = 3
println("x = y + 2:   ", x += 2)
println("y = y - 2:   ", y -= 2)
println("x = x * 10:  ", x *= 10)

println("----------------------------------------------------------")
## Comparison
println(4 == 4)
println(5 != 8)
println(3 <= 2)

Sum:              6.5
Subtract:         -4.5
Multiplication:   3
Division:         0.18181818181818182
Power:            166.375
----------------------------------------------------------
x = y + 2:   4
y = y - 2:   1
x = x * 10:  40
----------------------------------------------------------
true
true
false


## Operator precedence

#### When constructing expressions with multiple operators, the order in which these operators are applied to the expression is known as operator precedence.

In [3]:
x = 2
y = 3
z = 4
println(x*y+z^2)
println(x*(y+(z^2)))
println((x*y)+(z^2))

22
38
22


## Types
#### The Julia float type and all operations performed on it adhere to IEEE 754 standard (Zuras et al., 2018)
#### In Julia, a string is a sequence of Unicode code points, using UTF-8 encoding.
#### Char is a numeric value representing a Unicode code point

In [4]:
## Computer's architecture type
println(Sys.WORD_SIZE)

## Size of te default primitive
println(typemax(Int))

64
9223372036854775807


In [5]:
# Integers
int_1 = 1
println(typeof(int_1))
println("------------------------------------")

# Floats
f_1 = 1.0
f_2 = 15e-5
# Format Float32
f_3 = 2.5f-4
println(typeof(f_3))

# Digit separation 
println(7.4_4 == 7.44)

# Values Errors
println(isnan(0/0))
println(isinf(10/0))
println(isinf(10/0))
println("------------------------------------")

Int64
------------------------------------
Float32
true
true
true
true
------------------------------------
String
 I have a "quote" character 
------------------------------------


In [15]:
# Strings
# The strings are immutable, and are defined by double or triple quotes
s1 = "Hello world"
s2 = """ I have a "quote" character """
println(typeof(s2))
println(s2)

# Strings ca be sliced
my_string = "Julia is very fast"
println(my_string[1:8])
println(my_string[end])
println(my_string[end-3:end])

# The operator concatenation is *
my_string_2 = " and works for Data Science"
message = my_string * my_string_2
# Another way
message_2 = string(my_string, my_string_2)
println(message)
println(message_2)
println("------------------------------------")

String
 I have a "quote" character 
Julia is
t
fast
Julia is very fast and works for Data Science
Julia is very fast and works for Data Science
------------------------------------


### Strings can be compared lexicographically using comparison operators.
#### Some methods of strings are:
1. findfirst(pat, str)
2. occursin(substr, str)
3. repeat(str, n)
4. lenth(str)
5. replace(str, ptn => rep)

#### Julia fully supports regular expressions (regexes):
1. occursin(regex, str)
2. match(regex, str)
3. eachmatch(regex, str)

## Tuples 
#### Tuples are a Julia type. Fields are accessed by ther index, and are defined using brackets (). Tuples are inmmutables.

In [19]:
tup1 = (2., 5.6, 8.9, 2. ,5.)
tup2 = (8, "Julia", 9.0, 4.7, "Data")

println(typeof(tup1))
println(typeof(tup2))

a,b,c = ("Science", 9004, "Covid")
println(a)
println(b)
println(c)

NTuple{5,Float64}
Tuple{Int64,String,Float64,Float64,String}
Science
9004
Covid


## Arrays
#### An array is a multidimensional grid that stores objects of any type.

In [17]:
# Definition with type and dimension
a1 = Array{Int64}(undef, 5)
println(a1)

a2 = Array{Int64}(undef, (2,2))
println(a2)

[14, 17, 18, 19, 33]
[139839488038768 139839488038544; 139839488032208 139839764314512]


#### In Julia, [] can also be used to generate arrays.

#### Julia has many built-in functions that generate specific kinds of arrays. Here are some useful ones:
1. zeros(T, d1, ..)-------Matrix of zeros
2. ones(T, d1, ..)--------Matrix of ones
3. rand(T, d1, ..)--------Matrix of random numbers between 0 and 1
4. randn(T, d1, ..)-------Matrix of random numbers from the standar normal distribution
5. MatrixT(I, (n,n)-------Is the nxn identity matrix 
6. fill!(A, x)----------------Is the array A filled with value x

#### Note that, in te above, d1 can be a tuple specifying multiple dimensions.


#### Arrays can easily be concatenated in Julia:
1. vcat(A1, A2, ..) --------Concatenates arrays vertically
2. hcat(A1, A2, ..) --------Concatenates arrays hotizontally

In [34]:
# A vector
a3 = [1, 2, 3]

# A 1x3 column vector
a4 = [4 5 6]

# A matrix 2x3
m1 = [10 20 30 ; 90 91 92]

m2 = randn(Float64, (4,3))
m2

4×3 Array{Float64,2}:
 -0.905996   1.2278      0.174567
 -0.819067  -0.0149697  -1.57687
  0.821113  -0.215086    0.627307
  1.14005   -0.182964    0.863039

In [38]:
# Utils methods
println(length(m2))
println(size(m2))
println(ndims(m2))

m2_c = deepcopy(m2)

m2_r = reshape(m2, (3,4))

12
(4, 3)
2


3×4 Array{Float64,2}:
 -0.905996   1.14005    -0.215086  -1.57687
 -0.819067   1.2278     -0.182964   0.627307
  0.821113  -0.0149697   0.174567   0.863039

In [39]:
# Importing moduls
using LinearAlgebra
imat = Matrix{Int8}(I, (5,5))
imat

5×5 Array{Int8,2}:
 1  0  0  0  0
 0  1  0  0  0
 0  0  1  0  0
 0  0  0  1  0
 0  0  0  0  1

### Index

In [40]:
m2_r

3×4 Array{Float64,2}:
 -0.905996   1.14005    -0.215086  -1.57687
 -0.819067   1.2278     -0.182964   0.627307
  0.821113  -0.0149697   0.174567   0.863039

In [46]:
println(m2_r[1:3])
println(m2_r[1,:])
println(m2_r[:,1])
println(m2_r[1:end,2])

[-0.9059955220712619, -0.8190668252048187, 0.8211126661345738]
[-0.9059955220712619, 1.1400518343114883, -0.21508574116273774, -1.5768736848782388]
[-0.9059955220712619, -0.8190668252048187, 0.8211126661345738]
[1.1400518343114883, 1.2277987994134505, -0.01496965274292546]


### Comprehensions

In [48]:
A1 = [sqrt(i) for i in [1,4,9,16,25]]
println(A1)

A2 = [i^2 for i in [1,2,3,4,5]]
println(A2)

[1.0, 2.0, 3.0, 4.0, 5.0]
[1, 4, 9, 16, 25]
